# Find CEGUI includes and library
#
# This module defines
#  CEGUI_INCLUDE_DIR
#  CEGUI_LIBRARIES, the libraries to link against to use CEGUI.
#  CEGUI_FOUND, If false, do not try to use CEGUI
#
# Redistribution and use is allowed according to the terms of the BSD license.

IF (CEGUI_LIBRARIES AND CEGUI_INCLUDE_DIR)
    SET(CEGUI_FIND_QUIETLY TRUE) # Already in cache, be silent
ENDIF (CEGUI_LIBRARIES AND CEGUI_INCLUDE_DIR)


FIND_PATH( CEGUI_INCLUDE_DIR "CEGUI.h"
           PATH_SUFFIXES "CEGUI" )

FIND_LIBRARY( CEGUI_BASE_LIBRARY
              NAMES "CEGUIBase"
              PATH_SUFFIXES "CEGUI" )
              
FIND_LIBRARY( CEGUI_OGRE_RENDERER_LIBRARY
              NAMES "CEGUIOgreRenderer"
              PATH_SUFFIXES "CEGUI" )
              
SET( CEGUI_MEDIA_SEARCH_SUFFIX 
    CEGUI
    share/CEGUI
)

FIND_PATH( CEGUI_MEDIA_DIR NAMES looknfeel/TaharezLook.looknfeel PATHS ${CEGUI_PREFIX_PATH} PATH_SUFFIXES ${OGRE_MEDIA_SEARCH_SUFFIX})

SET( CEGUI_LIBRARIES ${CEGUI_BASE_LIBRARY} ${CEGUI_OGRE_RENDERER_LIBRARY} )

IF (CEGUI_INCLUDE_DIR AND CEGUI_LIBRARIES)
    SET(CEGUI_FOUND TRUE)
ENDIF (CEGUI_INCLUDE_DIR AND CEGUI_LIBRARIES)

IF (CEGUI_FOUND)
    IF (NOT CEGUI_FIND_QUIETLY)
        MESSAGE(STATUS "Found CEGUI: ${CEGUI_LIBRARIES} ${CEGUI_INCLUDE_DIR}")
    ENDIF (NOT CEGUI_FIND_QUIETLY)
ELSE (CEGUI_FOUND)
    IF (CEGUI_FIND_REQUIRED)
        MESSAGE(FATAL_ERROR "Could not find CEGUI")
    ENDIF (CEGUI_FIND_REQUIRED)
ENDIF (CEGUI_FOUND)

MARK_AS_ADVANCED( CEGUI_INCLUDE_DIR CEGUI_LIBRARIES CEGUI_BASE_LIBRARY CEGUI_OGRE_RENDERER_LIBRARY )
